const tool = require('../tool/data.tool');
const axios = require('axios');
const { refershSpotifyToken } = require('./link.account.service');


async function getLikedTracks({ username }) {
    const token = await refershSpotifyToken({ username });
    return await axios.get("https://api.spotify.com/v1/me/tracks?limit=10", {
        headers: {
            Authorization: `Bearer ${token}`
        }
    }).then((response) => {
        if (response.status === 200) {
            let listUriTracks = [];
            response.data.items.map(i => listUriTracks.push(i.track.uri));
            return listUriTracks;
        }
    }).catch((err) => {
        console.log(`erreur 'getLikedTracks' : ${err.response.status}, ${err.response.data}`);
        return null;
    });
}

async function createPlaylist({ usernameAsk, idAsk, usernameTarget, listTracks }) {
    let idPlaylist;
    const token = await refershSpotifyToken({ username: usernameAsk });
    await axios.post(`https://api.spotify.com/v1/users/${idAsk}/playlists`, {
        name: `Top Tracks of ${usernameTarget}`,
        description: `Playlist automatically generated by Yspotify`,
        public: false
    }, {
        headers: {
            Authorization: `Bearer ${token}`
        }
    }).then((response) => {
        if (response.status === 201) {
            idPlaylist = response.data.id;
        }
    }).catch((err) => {
        console.log(`erreur 'createPlaylist' création de la playlist : ${err.response.status}, ${err.response.data}`);

    });

    let res;
    if (idPlaylist) {
        await axios.post(`https://api.spotify.com/v1/playlists/${idPlaylist}/tracks`, {
            uris: listTracks,
            position: 0
        }, {
            headers: {
                Authorization: `Bearer ${token}`
            }
        }).then((response) => {
            if (response.status === 201) {
                res = response.data;
            }
        }).catch((err) => {
            res = null;
            console.log(`erreur 'createPlaylist' ajout des musiques : ${err.response.status}, ${err.response.data}`);
        });
    }
    return res
}

module.exports = {
    getLikedTracks,
    createPlaylist
}